### ISSUE TITLE
bug:search bar in settings not working properly

### ISSUE THREAD

**Issue by abhishekkumar08** [dabit3/react-native-hackathon-starter#120]
**Explain what you did (Required)**
I was testing the react-native-elements-app. In this settings section the input search bar doesn't let me type anything. As soon as I enter anything the `onChange()` clears it.

** To Reproduce **
1. Use the react-native-elements-app
2. Go to the setting section.
3. Try to write in the search bar.

**Screenshots (Required)**

https://user-images.githubusercontent.com/59651136/110808698-42b2d700-82aa-11eb-9b4d-3ec7d31983b8.mp4

**Your Environment (Required):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |         |
| react-native          |         |

**Comment by HariAcidReign** [comment]
@abhishekkumar08 Good catch, but I think this one was intentional as this repo is only for showing the visual aspects of React Native Elements and not their functionality.
So, to stop this bug, the developer has to add an `onChangeText={...callTheTextChangeHandler...}` which they will do in their own app as per their requirements. 
So, TLDR I think nothing can be done here. 🙌🏻
